spring:
  h2:
    console:
      enabled: true  # H2 콘솔 활성화
  datasource:
    url: jdbc:h2:tcp://localhost/~/test  # H2 TCP 모드 URL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    open-in-view: false  # LazyLoading 시 에러 방지
    show-sql: true  # SQL 쿼리 출력
    hibernate:
      ddl-auto: update  # 스키마 업데이트
      dialect: org.hibernate.dialect.H2Dialect  # H2 방언 설정
    properties:
      hibernate:
        format_sql: true  # SQL 포맷팅
  output:
    ansi:
      enabled: always  # ANSI 컬러 출력 활성화
  logging:
    level:
#      org.hibernate.SQL: debug  # SQL 쿼리 디버깅 로그
      org.hibernate.type: trace  # 바인딩된 파라미터 값 추적
