spring:
  # H2 설정
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    # LazyLoading 시 에러 방지
    open-in-view: false
    # SQL 쿼리 출력
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        # SQL 포맷팅
        format_sql: true
  output:
    ansi:
      enabled: always
  logging:
    level:
      # SQL 쿼리 디버깅 로그
      #org.hibernate.SQL: debug
      org.hibernate.type: trace
