server:
  port: 8081  # 포트를 8081로 설정

spring:
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:tcp://localhost:/data/h2/test
      driver-class-name: org.h2.Driver
      username: sa

  jpa:
    open-in-view: false
    # JPA가 수행하는 SQL을 볼 수 있다.
    show-sql: true
    # 객체를 보고 자동으로 테이블 생성 여부. 생성 - create, 비생성 - none
    # 테스트이기 때문에 create로 설정하며
    # 실제로는 none 으로 합니다. create이면 기존의 테이블을 전부 밀어버립니다.
    hibernate:
      ddl-auto: create
  # 콘솔 확인 을 위한 always
  output:
    ansi:
      enabled: always
# 파라미터 확인을 위한 trace
logging:
  level:
    org.hibernate.type: trace